# Change these first
owner: Emisys # Your GitHub organization or username, where this repository lives
repo: audience-status-page # The name of this repository

sites:
  - name: Au* Ticketing
    url: https://ticketing.byemisys.com
  - name: Au* Pos
    url: https://pos.byemisys.com
  - name: Au* Kiosk
    url: https://kiosk.byemisys.com
  - name: Au* Backoffice
    url: https://audience.byemisys.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /audience-status-page
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Audience
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
