# Change these first
owner: Emisys # Your GitHub organization or username, where this repository lives
repo: audience-status-page # The name of this repository

sites:
  - name: Au* Ticketing
    url: https://ticketing.byemisys.com
  - name: Au* Pos
    url: https://pos.byemisys.com
  - name: Au* Kiosk
    url: https://kiosk.byemisys.com
  - name: Au* Backoffice
    url: https://audience.byemisys.com

status-website:
  cname: status.byemisys.com
  baseUrl: /
  logoUrl: https://ticketing.byemisys.com/favicon/favicon_light.png
  name: Audience Status
  introTitle: "This is **Audience’s** status page, where you can get updates on how our systems are doing. If there are interruptions to service, we will post a note here."
  introMessage: "If you are experiencing any issues with Audience, don’t hesitate to get in touch with us at support-tech@emisys.com and we’ll get back to you as soon as we can."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
